// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr0aDM4exLJlIaOPKkr-Cd-8aToN7Wo84',
    appId: '1:916153726248:web:fc0e8b43d164517ee8cc1d',
    messagingSenderId: '916153726248',
    projectId: 'aplikasi-cuaca-dd7ba',
    authDomain: 'aplikasi-cuaca-dd7ba.firebaseapp.com',
    storageBucket: 'aplikasi-cuaca-dd7ba.firebasestorage.app',
    measurementId: 'G-D6689KDTCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAieO-xySLc8YTmsE_gsDlWlx4rzKLOVk',
    appId: '1:916153726248:android:d545303329060abce8cc1d',
    messagingSenderId: '916153726248',
    projectId: 'aplikasi-cuaca-dd7ba',
    storageBucket: 'aplikasi-cuaca-dd7ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPyinJjjLk2wpPnnNsqOV9sFnWJkoRTqc',
    appId: '1:916153726248:ios:d88e7812e309ad75e8cc1d',
    messagingSenderId: '916153726248',
    projectId: 'aplikasi-cuaca-dd7ba',
    storageBucket: 'aplikasi-cuaca-dd7ba.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiCuaca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPyinJjjLk2wpPnnNsqOV9sFnWJkoRTqc',
    appId: '1:916153726248:ios:d88e7812e309ad75e8cc1d',
    messagingSenderId: '916153726248',
    projectId: 'aplikasi-cuaca-dd7ba',
    storageBucket: 'aplikasi-cuaca-dd7ba.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiCuaca',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr0aDM4exLJlIaOPKkr-Cd-8aToN7Wo84',
    appId: '1:916153726248:web:7879180fc9ee8979e8cc1d',
    messagingSenderId: '916153726248',
    projectId: 'aplikasi-cuaca-dd7ba',
    authDomain: 'aplikasi-cuaca-dd7ba.firebaseapp.com',
    storageBucket: 'aplikasi-cuaca-dd7ba.firebasestorage.app',
    measurementId: 'G-693Q4TRXLY',
  );
}
